name: reaction-free-energy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyyaml
  - matplotlib
  - networkx
  - pyarrow
  - rdkit
  - ase
  - tblite-python
  - pip:
      - pydantic>=2
      - typer>=0.12
